import { StyleSheet } from 'react-native';
import { spacing } from '../../lib/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  topSearchBar: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    gap: spacing.sm,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    height: 40,
    fontSize: 13,
  },
  viewModeToggle: {
    flexDirection: 'row',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#013369',
    overflow: 'hidden',
  },
  perspectiveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  mobileTabSwitcher: {
    flexDirection: 'row',
    gap: 6,
  },
  mobileTabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
  },
  mainLayout: {
    flex: 1,
  },
  sidebarList: {
    backgroundColor: '#FFFFFF',
  },
  sidebarHeader: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    gap: 2,
  },
  categoryAccordion: {
    borderBottomWidth: 1,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  countBadge: {
    backgroundColor: '#EEF5F0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  unitsSublist: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    gap: 6,
    backgroundColor: '#FAFAFA',
  },
  unitSidebarItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.sm,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E5E8E2',
    backgroundColor: '#FFFFFF',
  },
  unitSidebarItemSelected: {
    backgroundColor: '#F0F7FF',
    borderColor: '#013369',
    borderLeftWidth: 4,
    borderLeftColor: '#013369',
  },
  beoIndicator: {
    backgroundColor: '#FDF3E3',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#E8D2A8',
  },
  mapCanvas: {
    flex: 1,
    backgroundColor: '#0A1118',
    position: 'relative',
  },
  interactiveModelFrame: {
    width: '100%',
    overflow: 'hidden',
    backgroundColor: '#08131F',
  },
  canvasHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    gap: spacing.sm,
  },
  levelFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  levelPill: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 4,
    borderWidth: 1,
  },
  canvasScrollInner: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stadium3DContainer: {
    padding: spacing.md,
    alignItems: 'center',
  },
  stadiumPerspectiveWrapper: {
    alignItems: 'center',
    gap: spacing.sm,
  },
  isometricTransform: {
    transform: [{ perspective: 1200 }, { rotateX: '18deg' }],
  },
  planTransform: {
    transform: [],
  },

  /* ── Roof Structure ── */
  roofTrussSuperstructure: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 12,
    marginVertical: 2,
  },
  roofRailTrack: {
    flex: 1,
    height: 3,
    backgroundColor: '#37474F',
    borderRadius: 2,
  },
  roofBadgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#ECEFF1',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    marginHorizontal: 8,
    borderWidth: 1,
    borderColor: '#CFD8DC',
  },
  roofBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#013369',
    letterSpacing: 0.5,
  },
  ringLabelHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  xfinityBadge: {
    backgroundColor: '#8A2BE2',
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  xfinityText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: '900',
  },
  /* ── 3D Gate Tower Architectural Structures ── */
  gateNorthWrapper: {
    width: '94%',
    alignItems: 'center',
    zIndex: 10,
  },
  gateSouthWrapper: {
    width: '94%',
    alignItems: 'center',
    zIndex: 10,
  },
  gateTowerStructure: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    borderRadius: 12,
    borderWidth: 2,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 8,
  },
  gateNorthTower: {
    backgroundColor: '#001E3D',
    borderColor: '#0055A5',
  },
  gateSouthTower: {
    backgroundColor: '#38070D',
    borderColor: '#C62828',
  },
  gatePylonPillarLeft: {
    width: 8,
    height: 36,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 4,
  },
  gatePylonPillarRight: {
    width: 8,
    height: 36,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 4,
  },
  gateTowerCenterHub: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  gateFordBadge: {
    backgroundColor: '#003366',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  gateFordText: {
    color: '#FFFFFF',
    fontStyle: 'italic',
    fontWeight: '900',
    fontSize: 15,
    letterSpacing: 1,
  },
  gateBadgeSub: {
    color: '#B0C4DE',
    fontSize: 7,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  gateKrogerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#D50A0A',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  gateKrogerText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 14,
  },
  gateTowerTitle: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 11,
    letterSpacing: 0.5,
  },
  turnstileBayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  turnstileCanopy: {
    width: 14,
    height: 3,
    backgroundColor: '#00E5FF',
    borderRadius: 2,
  },
  turnstileMetaText: {
    color: '#B0C4DE',
    fontSize: 9,
    fontWeight: '600',
  },
  gateTowerActive: {
    borderColor: '#FFD700',
    borderWidth: 3,
    transform: [{ translateY: -4 }, { scale: 1.02 }],
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 16,
    elevation: 16,
  },
  architecturalActiveBadge: {
    position: 'absolute',
    top: -10,
    right: 14,
    backgroundColor: '#FFD700',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  architecturalActiveBadgeText: {
    color: '#013369',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.5,
  },

  /* ── Side Gate Towers (West Phillips 66 & East Xfinity) ── */
  middleGatesSideRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: 6,
  },
  sideGateTowerWest: {
    width: 64,
    minHeight: 160,
    backgroundColor: '#1E0C10',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#C62828',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 6,
    gap: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  sideGateTowerEast: {
    width: 64,
    minHeight: 160,
    backgroundColor: '#1A0B28',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#7B1FA2',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 6,
    gap: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  p66Badge: {
    backgroundColor: '#D50A0A',
    borderRadius: 4,
    padding: 3,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  p66TextTop: {
    color: '#FFFFFF',
    fontSize: 6,
    fontWeight: '900',
  },
  p66TextBottom: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
  sideGateTowerText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  sideGatePylonFin: {
    width: '80%',
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    marginVertical: 2,
  },
  sideGateTowerSub: {
    color: '#B0BEC5',
    fontSize: 7,
    textAlign: 'center',
    fontWeight: '600',
  },
  sideGateActiveIndicator: {
    backgroundColor: '#FFD700',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    marginTop: 4,
  },
  sideGateActiveIndicatorText: {
    color: '#013369',
    fontSize: 7,
    fontWeight: '900',
  },

  /* ── Jumbotrons ── */
  jumbotronDisplayBox: {
    width: '86%',
    alignItems: 'center',
  },
  jumboScreenNorth: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#021224',
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#00E5FF',
    paddingVertical: 4,
    paddingHorizontal: 12,
    width: '100%',
    shadowColor: '#00E5FF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  jumboScreenSouth: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#021224',
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#00E5FF',
    paddingVertical: 4,
    paddingHorizontal: 12,
    width: '100%',
    shadowColor: '#00E5FF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  jumboScreenText: {
    color: '#00E5FF',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },

  /* ── Level 500/600 Upper Bowl: Grandstand Seating Sectors ── */
  outerUpperDeckRingRed: {
    width: '100%',
    backgroundColor: '#4A050D',
    borderRadius: 36,
    borderWidth: 3,
    borderColor: '#B71C1C',
    padding: spacing.sm,
    alignItems: 'center',
    gap: spacing.xs,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 14,
    elevation: 10,
  },
  stadiumTierBadgeRed: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#B71C1C',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#EF5350',
  },
  tierPillRedText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 10,
    letterSpacing: 0.5,
  },
  upperDeckSectors: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    gap: 6,
  },
  grandstandSeatingSection: {
    flex: 1,
    minHeight: 64,
    backgroundColor: '#7F131D',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#9E1C27',
    padding: 5,
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  grandstandSectionActive: {
    backgroundColor: '#B71C1C',
    borderColor: '#FFD700',
    borderWidth: 2.5,
    transform: [{ translateY: -5 }, { scale: 1.04 }],
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 14,
    elevation: 14,
  },
  grandstandFloodlightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  floodlightDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },
  floodlightDotActive: {
    backgroundColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 4,
  },
  grandstandSectionCode: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 11,
    letterSpacing: 0.5,
  },
  steppedSeatsContainer: {
    gap: 2,
    marginVertical: 2,
  },
  seatRowLine: {
    height: 2,
    backgroundColor: '#E57373',
    borderRadius: 1,
  },
  grandstandLowerDeck: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  grandstandTitleText: {
    flex: 1,
    color: '#FFCDD2',
    fontSize: 9,
    fontWeight: '700',
  },
  vomitoryTunnelArch: {
    backgroundColor: '#260307',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    borderWidth: 0.5,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  vomitoryTunnelText: {
    color: '#B0BEC5',
    fontSize: 6,
    fontWeight: '800',
  },
  grandstandActiveHalo: {
    position: 'absolute',
    top: -8,
    right: 4,
    backgroundColor: '#FFD700',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 3,
  },
  grandstandActiveHaloText: {
    color: '#013369',
    fontSize: 7,
    fontWeight: '900',
  },

  /* ── Level 300 & 400 Luxury Suites: Glass Cantilevered Pavilions ── */
  suitesTierRing: {
    flex: 1,
    backgroundColor: '#101720',
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#D4AF37',
    padding: spacing.xs,
    alignItems: 'center',
    gap: spacing.xs,
  },
  stadiumTierBadgeGold: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#7A5A1A',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#D4AF37',
  },
  tierPillGoldText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 10,
    letterSpacing: 0.5,
  },
  suitesGridRing: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
    gap: 6,
  },
  suitePavilionBox: {
    flexGrow: 1,
    flexBasis: 100,
    minHeight: 56,
    backgroundColor: '#1E2835',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#B8860B',
    overflow: 'hidden',
  },
  suitePavilionActive: {
    backgroundColor: '#2A3B4E',
    borderColor: '#FFD700',
    borderWidth: 2.5,
    transform: [{ translateY: -5 }, { scale: 1.04 }],
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 14,
    elevation: 14,
  },
  suiteGlassFacade: {
    backgroundColor: 'rgba(0, 229, 255, 0.12)',
    paddingVertical: 3,
    borderBottomWidth: 1,
    borderBottomColor: '#B8860B',
  },
  suiteBalconyRail: {
    height: 2,
    backgroundColor: '#D4AF37',
    width: '100%',
    marginBottom: 2,
  },
  suiteCodeText: {
    fontSize: 11,
    fontWeight: '900',
  },
  suiteBeoChip: {
    backgroundColor: '#7A5A1A',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
  },
  suiteBeoChipText: {
    color: '#FFD700',
    fontSize: 7,
    fontWeight: '900',
  },
  suiteLoungeInterior: {
    padding: 4,
  },
  suiteholderText: {
    fontSize: 10,
    fontWeight: '800',
  },
  suiteTierSub: {
    fontSize: 8,
    fontWeight: '600',
  },
  suiteActiveBadge: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: '#FFD700',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
  },
  suiteActiveBadgeText: {
    color: '#013369',
    fontSize: 7,
    fontWeight: '900',
  },

  /* ── Level 200 Club Level: Curved Terrace ── */
  clubTierRing: {
    width: '98%',
    backgroundColor: '#071524',
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#1E3A5F',
    padding: 6,
    alignItems: 'center',
    gap: spacing.xs,
  },
  ribbonLedDisplay: {
    width: '100%',
    backgroundColor: '#001020',
    borderRadius: 4,
    paddingVertical: 3,
    paddingHorizontal: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#00E5FF',
  },
  ribbonLedText: {
    color: '#00E5FF',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
  },
  clubSectorsRow: {
    flexDirection: 'row',
    width: '100%',
    gap: 6,
  },
  clubTerraceSection: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 42,
    backgroundColor: '#0E2238',
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#1E4976',
    paddingHorizontal: 8,
  },
  clubTerraceActive: {
    backgroundColor: '#013369',
    borderColor: '#FFD700',
    borderWidth: 2.5,
    transform: [{ translateY: -4 }, { scale: 1.03 }],
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 12,
    elevation: 12,
  },
  clubArmchairIndicator: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 229, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clubTerraceTitle: {
    fontSize: 11,
    fontWeight: '800',
  },
  clubTerraceSub: {
    fontSize: 8,
    color: '#81D4FA',
  },
  clubActivePill: {
    backgroundColor: '#FFD700',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
  },
  clubActivePillText: {
    color: '#013369',
    fontSize: 7,
    fontWeight: '900',
  },

  /* ── Level 100 Main Concourse: Culinary Storefront Plazas ── */
  concourseLevelRing: {
    width: '98%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#CBD5CD',
    padding: 6,
    alignItems: 'center',
    gap: 6,
  },
  stadiumTierBadgeNavy: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#013369',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 6,
  },
  tierPillNavyText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 10,
    letterSpacing: 0.5,
  },
  concoursePerimeterRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-around',
    gap: 6,
  },
  concourseHubStorefront: {
    flex: 1,
    minHeight: 46,
    justifyContent: 'center',
    backgroundColor: '#F1F6F2',
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#CBD5CD',
    overflow: 'hidden',
  },
  concourseAwningStripe: {
    height: 4,
    backgroundColor: '#013369',
    width: '100%',
  },
  concourseHubActive: {
    backgroundColor: '#013369',
    borderColor: '#FFD700',
    borderWidth: 2.5,
    transform: [{ translateY: -4 }, { scale: 1.03 }],
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 12,
    elevation: 12,
  },
  concourseHubCode: {
    fontSize: 11,
    fontWeight: '900',
  },
  concourseHubName: {
    fontSize: 9,
    fontWeight: '700',
  },

  /* ── Playing Field Core & Sideline Compounds ── */
  fieldAndSidelinesCore: {
    width: '100%',
    backgroundColor: '#01142F',
    borderRadius: 14,
    padding: 6,
    gap: 4,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  endzoneRowWrapper: {
    flexDirection: 'row',
    width: '100%',
    gap: 6,
  },
  fieldBunkerVault: {
    flex: 1,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#D4AF37',
    backgroundColor: '#382510',
    padding: 6,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  fieldBunkerVaultActive: {
    backgroundColor: '#7A5A1A',
    borderColor: '#FFD700',
    borderWidth: 2.5,
    transform: [{ translateY: -4 }, { scale: 1.03 }],
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 12,
    elevation: 12,
  },
  fieldBunkerTitle: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 11,
  },
  fieldBunkerSub: {
    color: '#E8D2A8',
    fontSize: 8,
    fontWeight: '600',
  },
  bunkerActiveTag: {
    backgroundColor: '#FFD700',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
  },
  bunkerActiveTagText: {
    color: '#013369',
    fontSize: 7,
    fontWeight: '900',
  },

  endzoneTurfSection: {
    flex: 1.6,
    borderRadius: 6,
    padding: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    backgroundColor: '#00143F',
  },
  goalpostStanchion: {
    position: 'absolute',
    top: 2,
  },
  goalpostIcon: {
    color: '#FFD700',
    fontSize: 10,
    fontWeight: '900',
  },
  endzoneTurfText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 13,
    letterSpacing: 2,
  },
  endzoneTurfSub: {
    color: '#90CAF9',
    fontSize: 8,
    fontWeight: '600',
  },

  centerFieldAndSidelinesRow: {
    flexDirection: 'row',
    width: '100%',
    minHeight: 130,
    gap: 6,
  },
  sidelineBenchTurf: {
    width: 72,
    borderRadius: 6,
    padding: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    backgroundColor: '#001E3D',
    gap: 2,
  },
  sidelineBenchText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 9,
    textAlign: 'center',
  },
  sidelineBenchSub: {
    color: '#81D4FA',
    fontSize: 7,
    textAlign: 'center',
  },
  sidelineYardMarkerPylon: {
    width: 6,
    height: 6,
    backgroundColor: '#FF5722',
    borderRadius: 3,
  },
  fieldPartActive: {
    borderColor: '#FFD700',
    borderWidth: 2.5,
    backgroundColor: '#013369',
    transform: [{ translateY: -4 }, { scale: 1.03 }],
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 14,
    elevation: 14,
  },

  actualPlayingField: {
    flex: 1,
    backgroundColor: '#1E6F3B',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  fieldYardGrid: {
    position: 'absolute',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  yardNumText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '800',
    opacity: 0.85,
  },
  midfieldLogoCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(1, 20, 63, 0.75)',
    borderRadius: 50,
    padding: 8,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },

  /* ── Level 0 Lockers Compound ── */
  undergroundLockerCompound: {
    width: '100%',
    backgroundColor: '#0A121A',
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#263238',
    padding: spacing.sm,
    gap: 6,
  },
  stadiumTierBadgeDark: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#263238',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 6,
  },
  tierPillDarkText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 10,
    letterSpacing: 0.5,
  },
  lockersGridRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  lockerRoomCompoundCard: {
    flexGrow: 1,
    flexBasis: 160,
    padding: 6,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#37474F',
    gap: 2,
  },
  lockerRoomActive: {
    borderColor: '#FFD700',
    borderWidth: 2.5,
    backgroundColor: '#013369',
    transform: [{ translateY: -4 }, { scale: 1.03 }],
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 12,
    elevation: 12,
  },
  lockerCodeText: {
    fontSize: 11,
    fontWeight: '900',
  },
  lockerNameText: {
    fontSize: 10,
    fontWeight: '700',
  },
  lockerActiveDot: {
    alignSelf: 'flex-end',
    backgroundColor: '#FFD700',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
  },
  lockerActiveDotText: {
    color: '#013369',
    fontSize: 7,
    fontWeight: '900',
  },

  /* ── Floating BEO & Amenities HUD Pop-Up ── */
  floatingBeoHudOverlay: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.97)',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FFD700',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 20,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  floatingBeoHudHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#ECEFF1',
    paddingBottom: 6,
  },
  glowingBeaconDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1.0,
    shadowRadius: 6,
  },
  floatingBeoHudCode: {
    fontSize: 12,
    fontWeight: '900',
    color: '#013369',
  },
  floatingBeoZonePill: {
    fontSize: 10,
    fontWeight: '700',
    color: '#68706A',
    backgroundColor: '#ECEFF1',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  floatingBeoHudTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1D2420',
  },
  floatingBeoContentBody: {
    gap: 6,
  },
  beoDetailsBox: {
    backgroundColor: '#FFFDF9',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8D2A8',
    padding: 8,
    gap: 4,
  },
  beoNumberLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#8A5D23',
  },
  beoStatusTag: {
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  beoStatusTagText: {
    color: '#2E7D32',
    fontSize: 8,
    fontWeight: '800',
  },
  beoPackageTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1D2420',
  },
  beoSuiteholderText: {
    fontSize: 11,
    color: '#68706A',
  },
  beoItemsList: {
    gap: 2,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: '#F0E6D2',
    paddingTop: 4,
  },
  beoItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  beoItemQty: {
    fontSize: 10,
    fontWeight: '800',
    color: '#8A5D23',
    width: 24,
  },
  beoItemName: {
    flex: 1,
    fontSize: 10,
    color: '#1D2420',
  },
  beoItemStatus: {
    fontSize: 8,
    fontWeight: '800',
    color: '#2E7D32',
  },
  standAmenitiesBox: {
    backgroundColor: '#F0F7FF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#B0D4FF',
    padding: 8,
    gap: 3,
  },
  standConceptHeader: {
    fontSize: 11,
    fontWeight: '800',
    color: '#013369',
  },
  standConceptDesc: {
    fontSize: 11,
    color: '#1D2420',
  },
  standMetricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  standMetricItem: {
    fontSize: 10,
    color: '#68706A',
  },
  floatingHudActionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 2,
  },
  hudPrimaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#013369',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 6,
  },
  hudPrimaryBtnText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 11,
  },

  // ── SUITE FLOOR SELECTOR & DROPDOWN STYLES ──
  suiteFloorTabsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 4,
    backgroundColor: '#FAF5EA',
    borderBottomWidth: 1,
    borderBottomColor: '#F0E6D2',
  },
  suiteFloorTabBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2D4B7',
  },
  suiteFloorTabBtnActive: {
    backgroundColor: '#8A5D23',
    borderColor: '#684518',
  },
  suiteFloorTabText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#684518',
  },
  suiteFloorTabTextActive: {
    color: '#FFFFFF',
  },
  suiteDropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginHorizontal: 8,
    marginTop: 6,
    marginBottom: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#DFCBB0',
  },
  suiteDropdownTriggerOpen: {
    borderColor: '#8A5D23',
    backgroundColor: '#FFFDF9',
  },
  suiteDropdownTriggerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
    marginRight: 8,
  },
  suiteDropdownTriggerText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1D2420',
    flex: 1,
  },
  suiteDropdownTriggerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  suiteDropdownTriggerCount: {
    fontSize: 10,
    fontWeight: '800',
    color: '#8A5D23',
    backgroundColor: '#FDF7EB',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  suiteDropdownMenuBox: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 8,
    marginBottom: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8A5D23',
    padding: 8,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
  },
  suiteDropdownSearchRow: {
    marginBottom: 6,
  },
  suiteDropdownSearchInput: {
    backgroundColor: '#FDFBF7',
    fontSize: 11,
    height: 36,
  },
  suiteDropdownScrollList: {
    maxHeight: 220,
  },
  suiteDropdownItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F5EFE6',
  },
  suiteDropdownItemRowActive: {
    backgroundColor: '#F7F1E5',
    borderBottomColor: '#E2D4B7',
  },
  suiteDropdownItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  suiteStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  suiteDropdownItemNumber: {
    fontSize: 11,
    fontWeight: '800',
    color: '#8A5D23',
  },
  suiteDropdownItemHolder: {
    fontSize: 11,
    fontWeight: '600',
    color: '#1D2420',
    flexShrink: 1,
  },
  suiteDropdownItemTier: {
    fontSize: 9,
    color: '#78909C',
    marginTop: 1,
  },
  suiteDropdownItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginLeft: 6,
  },
  suiteDropdownBeoPill: {
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
  },
  suiteDropdownBeoPillText: {
    fontSize: 8,
    fontWeight: '800',
    color: '#2E7D32',
  },
  suiteDropdownOpenText: {
    fontSize: 8,
    fontWeight: '700',
    color: '#90A4AE',
  },

  // ── FOCUSED ACTIVE SUITE DISPLAY CARD (CLEAN DROPDOWN-DRIVEN UX) ──
  activeSuiteFocusCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#DFD2BC',
    padding: 12,
    marginTop: 8,
    gap: 10,
    shadowColor: '#8A5D23',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  activeSuiteFocusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F0E6D2',
  },
  activeSuiteBadgeIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#013369',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeSuiteFocusTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#013369',
  },
  suiteBeoActiveBadge: {
    backgroundColor: '#E8F5E9',
    borderColor: '#2E7D32',
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  suiteBeoActiveBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#2E7D32',
  },
  suiteOpenActiveBadge: {
    backgroundColor: '#F5F5F5',
    borderColor: '#B0BEC5',
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  suiteOpenActiveBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#546E7A',
  },
  activeSuiteFocusSub: {
    fontSize: 11,
    color: '#78909C',
    marginTop: 2,
  },
  activeSuiteDetailsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    backgroundColor: '#FAF5EC',
    padding: 10,
    borderRadius: 8,
  },
  activeSuiteDetailItem: {
    flex: 1,
    minWidth: 140,
  },
  activeSuiteDetailLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: '#8A5D23',
    letterSpacing: 0.5,
  },
  activeSuiteDetailVal: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1D2420',
    marginTop: 2,
  },
  activeSuiteActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  activeSuitePrimaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFD700',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 6,
  },
  activeSuitePrimaryBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#013369',
  },
  activeSuiteChangeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderColor: '#DFD2BC',
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 6,
  },
  activeSuiteChangeBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#8A5D23',
  },
  suitePlaceholderPromptBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 14,
    marginTop: 8,
    backgroundColor: '#FAF5EC',
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#DFD2BC',
  },
  suitePlaceholderPromptText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8A5D23',
  },
});
