import type { StadiumZoneItem } from '../StadiumUnitDetailModal';

export interface StadiumZoneData {
  id: string;
  name: string;
  code: string;
  level: string;
  department: string;
  category:
    | 'field_sidelines'
    | 'concourse_bunkers'
    | 'concourse_service_areas'
    | 'locker_rooms_aux'
    | 'luxury_suites'
    | 'club_level'
    | 'upper_deck'
    | 'stadium_gates'
    | 'commissary_boh';
  unitsCount: number;
  openCount: number;
  alertCount: number;
  units: StadiumZoneItem[];
}

export const COMPREHENSIVE_STADIUM_ZONES: StadiumZoneData[] = [
  // ── 1. FIELD, SIDELINES & ENDZONES ──────────────────────────────────────
  {
    id: 'zone-field-sidelines',
    name: 'Field Level, Sidelines & Endzones',
    code: 'FIELD-SIDE',
    level: '0',
    department: 'field_operations',
    category: 'field_sidelines',
    unitsCount: 4,
    openCount: 4,
    alertCount: 0,
    units: [
      {
        id: 'u-side-home',
        code: 'SIDE-HOME',
        name: 'Home Sideline Service Area & Hydration Station',
        department: 'field_operations',
        type: 'sideline_service_area',
        capacity: 120,
        stadiumZone: 'West Field Perimeter',
        level: '0',
        status: 'open',
        standDetails: {
          standNumber: 'SIDE-H-01',
          concept: 'Team Performance Hydration & VIP Sideline Hospitality',
          terminalCount: 2,
          cashGrossCents: 450000,
          inSeatOrders: [
            { id: 'side-h-1', seatLocation: 'Home Sideline Bench VIP 1', customerName: 'Team Ops Lead', orderedAt: '1:10 PM', items: '24x Electrolyte Carafes, 12x Chilled Towels', totalCents: 0, status: 'delivered', runnerName: 'Runner David K.' },
            { id: 'side-h-2', seatLocation: 'Home Bench Row A', customerName: 'Media VIP Passholder', orderedAt: '1:35 PM', items: '2x Cold Brew, 2x Protein Fuel Packs', totalCents: 2400, status: 'delivered', runnerName: 'Runner David K.' },
          ],
          hierarchy: {
            director: { name: 'Derrick Vance', title: 'Director of Field & Gameday Operations', radioChannel: 'Ch 2 - Field Command' },
            manager: { name: 'Tariq Al-Mansoor', title: 'Sideline & Tunnel Operations Manager', status: 'on_duty', radioChannel: 'Ch 2 - Field Command' },
            assignedStaff: [
              { name: 'David Kim', role: 'Lead Field Hospitality Runner', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
              { name: 'Samantha Cruz', role: 'Sideline Hydration Attendant', status: 'on_duty', shift: '10:30 - Close', geofenceVerified: true },
              { name: 'Leo Martinez', role: 'Field Access Credential Escort', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-side-visiting',
        code: 'SIDE-VISIT',
        name: 'Visiting Sideline Service Area & Media Deck',
        department: 'field_operations',
        type: 'sideline_service_area',
        capacity: 120,
        stadiumZone: 'East Field Perimeter',
        level: '0',
        status: 'open',
        standDetails: {
          standNumber: 'SIDE-V-01',
          concept: 'Visiting Team Bench Service & Broadcast Crew Support',
          terminalCount: 2,
          cashGrossCents: 380000,
          inSeatOrders: [
            { id: 'side-v-1', seatLocation: 'Visiting Bench Station 2', customerName: 'Visiting Equipment Staff', orderedAt: '1:15 PM', items: '16x Isotonic Water Packs, Fresh Fruit Trays', totalCents: 0, status: 'delivered', runnerName: 'Runner Chloe B.' },
            { id: 'side-v-2', seatLocation: 'Field Broadcast Camera 4', customerName: 'Network Director', orderedAt: '1:40 PM', items: '4x Espresso Cans, 2x Chicken Wraps', totalCents: 3600, status: 'fulfilling', runnerName: 'Runner Chloe B.' },
          ],
          hierarchy: {
            director: { name: 'Derrick Vance', title: 'Director of Field & Gameday Operations', radioChannel: 'Ch 2 - Field Command' },
            manager: { name: 'Tariq Al-Mansoor', title: 'Sideline & Tunnel Operations Manager', status: 'on_duty', radioChannel: 'Ch 2 - Field Command' },
            assignedStaff: [
              { name: 'Chloe Bennett', role: 'Visiting Sideline Runner', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
              { name: 'Andre Washington', role: 'Broadcast Hospitality Attendant', status: 'on_duty', shift: '10:30 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-endzone-north',
        code: 'ENDZONE-N',
        name: 'North Endzone Goalpost Lounge & Mobile Depot',
        department: 'field_hospitality',
        type: 'endzone_lounge',
        capacity: 250,
        stadiumZone: 'North Field Endzone',
        level: '0',
        status: 'open',
        standDetails: {
          standNumber: 'EZ-N-100',
          concept: 'Field-Level Goalpost Bar & Endzone In-Seat Dispatch',
          terminalCount: 4,
          cashGrossCents: 890000,
          inSeatOrders: [
            { id: 'ez-n-1', seatLocation: 'North Endzone Field Row 1, Seat 12', customerName: 'Brandon Ross', orderedAt: '1:22 PM', items: '2x Double Smashburger, 2x Draft Hazy IPA', totalCents: 4800, status: 'delivered', runnerName: 'Runner Maya S.' },
            { id: 'ez-n-2', seatLocation: 'North Endzone Field Row 2, Seat 4', customerName: 'Jessica Taylor', orderedAt: '1:48 PM', items: '1x Loaded Pulled Pork Nachos, 2x Souvenir Soda', totalCents: 3400, status: 'fulfilling', runnerName: 'Runner Maya S.' },
          ],
          hierarchy: {
            director: { name: 'Eleanor Vance', title: 'VP of Premium Hospitality', radioChannel: 'Ch 1 - Executive' },
            manager: { name: 'Jason Sterling', title: 'Field Clubs & Endzone Manager', status: 'on_duty', radioChannel: 'Ch 3 - Concourse North' },
            assignedStaff: [
              { name: 'Maya Santos', role: 'Lead Field Runner', status: 'on_duty', shift: '11:00 - Close', geofenceVerified: true },
              { name: 'Craig O’Connor', role: 'Head Bartender', status: 'on_duty', shift: '11:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-endzone-south',
        code: 'ENDZONE-S',
        name: 'South Endzone Touchdown Terrace & Fan Deck',
        department: 'field_hospitality',
        type: 'endzone_lounge',
        capacity: 300,
        stadiumZone: 'South Field Endzone',
        level: '0',
        status: 'open',
        standDetails: {
          standNumber: 'EZ-S-100',
          concept: 'Open-Air Field Bar & High-Volume Mobile Order Pickup',
          terminalCount: 6,
          cashGrossCents: 1120000,
          inSeatOrders: [
            { id: 'ez-s-1', seatLocation: 'South Endzone Row 1, Seat 18', customerName: 'Tyler Hayes', orderedAt: '1:18 PM', items: '3x Craft Draft Lager, 1x Giant Bavarian Pretzel', totalCents: 5200, status: 'delivered', runnerName: 'Runner Liam P.' },
            { id: 'ez-s-2', seatLocation: 'South Endzone Row 3, Seat 8', customerName: 'Kelly Green', orderedAt: '1:52 PM', items: '2x Crispy Tenders Basket, 2x Lemonade', totalCents: 3800, status: 'fulfilling', runnerName: 'Runner Liam P.' },
          ],
          hierarchy: {
            director: { name: 'Eleanor Vance', title: 'VP of Premium Hospitality', radioChannel: 'Ch 1 - Executive' },
            manager: { name: 'Jason Sterling', title: 'Field Clubs & Endzone Manager', status: 'on_duty', radioChannel: 'Ch 3 - Concourse North' },
            assignedStaff: [
              { name: 'Liam Patel', role: 'Lead Field Runner', status: 'on_duty', shift: '11:00 - Close', geofenceVerified: true },
              { name: 'Zoe Morales', role: 'Bar Attendant', status: 'on_duty', shift: '11:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
    ],
  },

  // ── 2. CONCOURSE TWO BUNKERS ────────────────────────────────────────────
  {
    id: 'zone-concourse-bunkers',
    name: 'Concourse VIP Field Bunkers (2)',
    code: 'BUNKERS-100',
    level: '1',
    department: 'premium_hospitality',
    category: 'concourse_bunkers',
    unitsCount: 2,
    openCount: 2,
    alertCount: 0,
    units: [
      {
        id: 'u-bunker-north',
        code: 'BUNKER-NORTH',
        name: 'North Bunker Club & Field Vault',
        department: 'premium_hospitality',
        type: 'concourse_bunker',
        capacity: 180,
        stadiumZone: 'North Concourse Level 100 Tunnel Access',
        level: '1',
        status: 'open',
        suiteDetails: {
          suiteNumber: 'BUNKER-N',
          suiteholder: 'Founders Club Members & Field Suite All-Access',
          tier: 'Sub-Field Luxury Bunker',
          hostName: 'Chef Antoine DuBois (Executive Chef)',
          guestCount: 165,
          beoNumber: 'BEO-BUNKER-2026-N01',
          beoPackageName: 'Chef Action Carving & Top-Shelf Bourbon Vault',
          menuPackage: 'A5 Wagyu carving board, chilled King Crab legs, artisanal charcuterie, Allocated Bourbon & Champagne bar',
          attendantName: 'Rachel Green (Lead Sommelier)',
          beoPreOrders: [
            { id: 'bn-1', name: 'A5 Miyazaki Wagyu Strip Carving Station', quantity: 150, category: 'entree', status: 'delivered', scheduledTime: 'Kickoff - 45m' },
            { id: 'bn-2', name: 'Colossal Alaskan King Crab & Raw Bar Tower', quantity: 4, category: 'appetizer', status: 'delivered', scheduledTime: 'Pre-Game', dietaryNotes: 'Shellfish' },
            { id: 'bn-3', name: 'Pappy Van Winkle & Blanton’s Flight Bar', quantity: 180, category: 'bar', status: 'active', scheduledTime: 'All Game' },
            { id: 'bn-4', name: 'Warm Molten Valrhona Chocolate Lava Cakes', quantity: 150, category: 'dessert', status: 'prepped', scheduledTime: 'Halftime' },
          ],
          inSuiteOrders: [
            { id: 'iso-bn-1', orderedAt: '1:12 PM', orderedBy: 'Member Table 4', items: '2x Macallan 18yr Neat, 1x Osetra Caviar Service', totalCents: 45000, status: 'fulfilled' },
            { id: 'iso-bn-2', orderedAt: '1:45 PM', orderedBy: 'Member Table 8', items: '1x Truffle Fries Board, 2x Veuve Clicquot', totalCents: 32000, status: 'delivering' },
          ],
          hierarchy: {
            director: { name: 'Eleanor Vance', title: 'VP of Premium Hospitality', radioChannel: 'Ch 1 - Executive' },
            manager: { name: 'Dominic Rossi', title: 'Bunker Clubs General Manager', status: 'on_duty', radioChannel: 'Ch 5 - Bunker VIP' },
            assignedStaff: [
              { name: 'Rachel Green', role: 'Lead Sommelier & Host', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
              { name: 'Sean Connolly', role: 'Master Mixologist', status: 'on_duty', shift: '10:30 - Close', geofenceVerified: true },
              { name: 'Katelyn Miller', role: 'VIP Floor Attendant', status: 'on_duty', shift: '11:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-bunker-south',
        code: 'BUNKER-SOUTH',
        name: 'South Bunker Founders Lounge & Taproom',
        department: 'premium_hospitality',
        type: 'concourse_bunker',
        capacity: 160,
        stadiumZone: 'South Concourse Level 100 Tunnel Access',
        level: '1',
        status: 'open',
        suiteDetails: {
          suiteNumber: 'BUNKER-S',
          suiteholder: 'Apex Chairman & Legacy Suite Syndicate',
          tier: 'Sub-Field Luxury Bunker',
          hostName: 'Danielle Brooks',
          guestCount: 140,
          beoNumber: 'BEO-BUNKER-2026-S02',
          beoPackageName: 'Smoked Prime Brisket & Craft Reserve Taproom',
          menuPackage: '16-hr smoked Texas brisket, lobster mac & cheese, craft beer cellar, artisanal cocktail station',
          attendantName: 'Gabriel Torres (Lead Attendant)',
          beoPreOrders: [
            { id: 'bs-1', name: 'Texas Prime Brisket & Jalapeno Sausage Spread', quantity: 140, category: 'entree', status: 'delivered', scheduledTime: 'Kickoff - 30m' },
            { id: 'bs-2', name: 'Maine Lobster Mac & Cheese Skillets', quantity: 140, category: 'entree', status: 'delivered', scheduledTime: 'Kickoff' },
            { id: 'bs-3', name: 'Craft IPA & Microbrew Tasting Wall (12 Taps)', quantity: 140, category: 'bar', status: 'active', scheduledTime: 'All Game' },
            { id: 'bs-4', name: 'Artisan Bourbon Pecan Pie with Sweet Cream', quantity: 140, category: 'dessert', status: 'prepped', scheduledTime: 'Halftime' },
          ],
          inSuiteOrders: [
            { id: 'iso-bs-1', orderedAt: '1:25 PM', orderedBy: 'Bunker South Lounge Table 2', items: '1x Don Julio 1942 Bottle Service', totalCents: 48000, status: 'fulfilled' },
          ],
          hierarchy: {
            director: { name: 'Eleanor Vance', title: 'VP of Premium Hospitality', radioChannel: 'Ch 1 - Executive' },
            manager: { name: 'Dominic Rossi', title: 'Bunker Clubs General Manager', status: 'on_duty', radioChannel: 'Ch 5 - Bunker VIP' },
            assignedStaff: [
              { name: 'Gabriel Torres', role: 'Lead Attendant', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
              { name: 'Amber Lewis', role: 'Private Bartender', status: 'on_duty', shift: '10:30 - Close', geofenceVerified: true },
            ],
          },
        },
      },
    ],
  },

  // ── 3. CONCOURSE 8 SERVICE AREAS THROUGHOUT ─────────────────────────────
  {
    id: 'zone-concourse-service-areas',
    name: 'Concourse 100 Service Areas (8 Outlets)',
    code: 'CONC-8-AREAS',
    level: '1',
    department: 'concessions',
    category: 'concourse_service_areas',
    unitsCount: 8,
    openCount: 8,
    alertCount: 0,
    units: [
      {
        id: 'u-c101',
        code: 'SVC-101',
        name: 'East Concourse 101 · Yardline Smokehouse & BBQ',
        department: 'concessions',
        type: 'concourse_service_area',
        capacity: null,
        stadiumZone: 'East Concourse 100',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'ST-101',
          concept: 'Oak-Smoked Brisket, Pulled Pork, BBQ Platters',
          terminalCount: 6,
          cashBeginningCents: 60000,
          cashGrossCents: 1420000,
          lowStockItems: ['Apple Cider Slaw (8 portions remaining)'],
          inSeatOrders: [
            { id: 'c101-1', seatLocation: 'Sec 102, Row 14, Seat 5', customerName: 'Adam Reed', orderedAt: '1:24 PM', items: '2x Brisket Sandwich Combo, 2x Draft Beer', totalCents: 4400, status: 'delivered', runnerName: 'Runner Ben G.' },
          ],
          hierarchy: {
            director: { name: 'Marcus Sterling', title: 'Director of General Concessions', radioChannel: 'Ch 3 - Concessions Main' },
            manager: { name: 'Carlos Gutierrez', title: 'East Concourse 100 Stand Manager', status: 'on_duty', radioChannel: 'Ch 3 - Concessions Main' },
            assignedStaff: [
              { name: 'Ben Garcia', role: 'Head Smoke Cook', status: 'on_duty', shift: '09:30 - Close', geofenceVerified: true },
              { name: 'Hannah Wright', role: 'Cashier & POS Operator', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
              { name: 'Tony Vance', role: 'Expediter', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-c103',
        code: 'SVC-103',
        name: 'East Concourse 103 · Craft Beer & Draft Express Hub',
        department: 'concessions',
        type: 'concourse_service_area',
        capacity: null,
        stadiumZone: 'East Concourse 100',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'ST-103',
          concept: '24-Tap High-Speed Draft & Hard Seltzer Bar',
          terminalCount: 8,
          cashBeginningCents: 80000,
          cashGrossCents: 2150000,
          hierarchy: {
            director: { name: 'Marcus Sterling', title: 'Director of General Concessions', radioChannel: 'Ch 3 - Concessions Main' },
            manager: { name: 'Carlos Gutierrez', title: 'East Concourse 100 Stand Manager', status: 'on_duty', radioChannel: 'Ch 3 - Concessions Main' },
            assignedStaff: [
              { name: 'Samantha Cole', role: 'Lead Pour Master', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
              { name: 'Jordan Rivera', role: 'Draft Technician', status: 'on_duty', shift: '09:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-c108',
        code: 'SVC-108',
        name: 'North Concourse 108 · Goalpost Tacos & Cantina',
        department: 'concessions',
        type: 'concourse_service_area',
        capacity: null,
        stadiumZone: 'North Concourse 100',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'ST-108',
          concept: 'Birria Tacos, Street Corn, Frozen Margaritas',
          terminalCount: 6,
          cashBeginningCents: 60000,
          cashGrossCents: 1680000,
          hierarchy: {
            director: { name: 'Marcus Sterling', title: 'Director of General Concessions', radioChannel: 'Ch 3 - Concessions Main' },
            manager: { name: 'Valerie Gomez', title: 'North Concourse Stand Manager', status: 'on_duty', radioChannel: 'Ch 4 - Concessions North' },
            assignedStaff: [
              { name: 'Mateo Silva', role: 'Line Chef', status: 'on_duty', shift: '09:30 - Close', geofenceVerified: true },
              { name: 'Daniela Reyes', role: 'POS Cashier', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-c112',
        code: 'SVC-112',
        name: 'North Concourse 112 · Blitz Pretzel & Bavarian Taphouse',
        department: 'concessions',
        type: 'concourse_service_area',
        capacity: null,
        stadiumZone: 'North Concourse 100',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'ST-112',
          concept: 'Warm Jumbo Pretzels, Beer Cheese, German Pilsners',
          terminalCount: 4,
          cashBeginningCents: 40000,
          cashGrossCents: 980000,
          hierarchy: {
            director: { name: 'Marcus Sterling', title: 'Director of General Concessions', radioChannel: 'Ch 3 - Concessions Main' },
            manager: { name: 'Valerie Gomez', title: 'North Concourse Stand Manager', status: 'on_duty', radioChannel: 'Ch 4 - Concessions North' },
            assignedStaff: [
              { name: 'Lucas Meyer', role: 'Baking Attendant', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-c118',
        code: 'SVC-118',
        name: 'West Concourse 118 · 50-Yardline Prime Burger & Grille',
        department: 'concessions',
        type: 'concourse_service_area',
        capacity: null,
        stadiumZone: 'West Concourse 100',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'ST-118',
          concept: 'Certified Angus Smashburgers, Truffle Fries, Shakes',
          terminalCount: 8,
          cashBeginningCents: 80000,
          cashGrossCents: 2450000,
          hierarchy: {
            director: { name: 'Marcus Sterling', title: 'Director of General Concessions', radioChannel: 'Ch 3 - Concessions Main' },
            manager: { name: 'Derrick Hall', title: 'West Concourse Stand Manager', status: 'on_duty', radioChannel: 'Ch 3 - Concessions Main' },
            assignedStaff: [
              { name: 'Kevin O’Neal', role: 'Lead Grill Master', status: 'on_duty', shift: '09:00 - Close', geofenceVerified: true },
              { name: 'Ashley Cooper', role: 'Cashier & Expediter', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-c122',
        code: 'SVC-122',
        name: 'West Concourse 122 · High-Velocity Cocktails & Spirits',
        department: 'concessions',
        type: 'concourse_service_area',
        capacity: null,
        stadiumZone: 'West Concourse 100',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'ST-122',
          concept: 'Rapid-Pour Premium Spirits, Canned Cocktails, Wine',
          terminalCount: 6,
          cashBeginningCents: 60000,
          cashGrossCents: 1890000,
          hierarchy: {
            director: { name: 'Marcus Sterling', title: 'Director of General Concessions', radioChannel: 'Ch 3 - Concessions Main' },
            manager: { name: 'Derrick Hall', title: 'West Concourse Stand Manager', status: 'on_duty', radioChannel: 'Ch 3 - Concessions Main' },
            assignedStaff: [
              { name: 'Brittany Scott', role: 'Head Bartender', status: 'on_duty', shift: '10:30 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-c128',
        code: 'SVC-128',
        name: 'South Concourse 128 · Touchdown Pizza & Italian Kitchen',
        department: 'concessions',
        type: 'concourse_service_area',
        capacity: null,
        stadiumZone: 'South Concourse 100',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'ST-128',
          concept: 'Brick-Oven Style Slices, Garlic Knots, Italian Sodas',
          terminalCount: 6,
          cashBeginningCents: 60000,
          cashGrossCents: 1540000,
          hierarchy: {
            director: { name: 'Marcus Sterling', title: 'Director of General Concessions', radioChannel: 'Ch 3 - Concessions Main' },
            manager: { name: 'Marco Bellini', title: 'South Concourse Stand Manager', status: 'on_duty', radioChannel: 'Ch 4 - Concessions South' },
            assignedStaff: [
              { name: 'Gianna Rossi', role: 'Pizza Chef', status: 'on_duty', shift: '09:30 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-c134',
        code: 'SVC-134',
        name: 'South Concourse 134 · Gridiron Sweet Treats & Gelato',
        department: 'concessions',
        type: 'concourse_service_area',
        capacity: null,
        stadiumZone: 'South Concourse 100',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'ST-134',
          concept: 'Gourmet Churros, Gelato Cups, Funnel Cakes, Coffee',
          terminalCount: 4,
          cashBeginningCents: 40000,
          cashGrossCents: 820000,
          hierarchy: {
            director: { name: 'Marcus Sterling', title: 'Director of General Concessions', radioChannel: 'Ch 3 - Concessions Main' },
            manager: { name: 'Marco Bellini', title: 'South Concourse Stand Manager', status: 'on_duty', radioChannel: 'Ch 4 - Concessions South' },
            assignedStaff: [
              { name: 'Emily Clark', role: 'Dessert Station Lead', status: 'on_duty', shift: '10:30 - Close', geofenceVerified: true },
            ],
          },
        },
      },
    ],
  },

  // ── 4. LOCKER ROOMS & AUXILIARY PERFORMER ROOMS ─────────────────────────
  {
    id: 'zone-locker-rooms-aux',
    name: 'Team Locker Rooms & Auxiliary Performer Suites',
    code: 'LOCKERS-BOH',
    level: '0',
    department: 'facilities_operations',
    category: 'locker_rooms_aux',
    unitsCount: 6,
    openCount: 6,
    alertCount: 0,
    units: [
      {
        id: 'u-lck-home',
        code: 'LCK-HOME',
        name: 'Home Team Primary Locker Room & Fuel Kitchen',
        department: 'facilities_operations',
        type: 'team_locker_room',
        capacity: 85,
        stadiumZone: 'West Player Tunnel Level 0',
        level: '0',
        status: 'restricted',
        suiteDetails: {
          suiteNumber: 'HOME-LOCKER',
          suiteholder: 'Home NFL Franchise · Team Operations',
          tier: 'Athletic Compound',
          hostName: 'Dr. Robert Hayes (Head of Sports Performance)',
          guestCount: 68,
          beoNumber: 'BEO-ATHLETIC-2026-001',
          beoPackageName: 'High-Performance Gameday Athlete Nutrition',
          menuPackage: 'Sous-vide chicken breast, grilled salmon, organic quinoa bowls, custom smoothie bar, cold-press hydration',
          attendantName: 'Chef Malik Jackson',
          beoPreOrders: [
            { id: 'hl-1', name: 'Pre-Game High-Carb Fuel Buffet (Organic Rice, Sweet Potato, Salmon)', quantity: 65, category: 'entree', status: 'delivered', scheduledTime: 'Kickoff - 2h' },
            { id: 'hl-2', name: 'Post-Game Protein Recovery Station (Flank Steak, Grilled Veg)', quantity: 65, category: 'entree', status: 'prepped', scheduledTime: 'Post-Game' },
            { id: 'hl-3', name: 'Organic Cold-Pressed Juices & Electrolytes (100 Bottles)', quantity: 100, category: 'beverage', status: 'delivered', scheduledTime: 'Pre-Game' },
          ],
          hierarchy: {
            director: { name: 'Derrick Vance', title: 'Director of Field & Gameday Operations', radioChannel: 'Ch 2 - Field Command' },
            manager: { name: 'Franklin Pierce', title: 'Locker & Athlete Facilities Manager', status: 'on_duty', radioChannel: 'Ch 2 - Field Command' },
            assignedStaff: [
              { name: 'Chef Malik Jackson', role: 'Lead Performance Nutrition Chef', status: 'on_duty', shift: '07:00 - Close', geofenceVerified: true },
              { name: 'Darnell Harris', role: 'Athlete Service Attendant', status: 'on_duty', shift: '08:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-lck-visiting',
        code: 'LCK-VISIT',
        name: 'Visiting Team Official Locker Room & Training Quarters',
        department: 'facilities_operations',
        type: 'team_locker_room',
        capacity: 85,
        stadiumZone: 'East Player Tunnel Level 0',
        level: '0',
        status: 'restricted',
        suiteDetails: {
          suiteNumber: 'VISIT-LOCKER',
          suiteholder: 'Visiting NFL Franchise Delegation',
          tier: 'Athletic Compound',
          hostName: 'Visiting Travel Secretary',
          guestCount: 65,
          beoNumber: 'BEO-ATHLETIC-2026-002',
          beoPackageName: 'Visiting Delegation Pre & Post-Game Hospitality',
          menuPackage: 'Hot breakfast sandwiches, pre-game lean proteins, post-game charcuterie & recovery boxes',
          attendantName: 'Chef Sarah Collins',
          beoPreOrders: [
            { id: 'vl-1', name: 'Visiting Pre-Game Lean Protein Buffet', quantity: 60, category: 'entree', status: 'delivered', scheduledTime: 'Kickoff - 2h' },
            { id: 'vl-2', name: 'Post-Game Travel Boxed Meals (Steak / Salmon / Vegan)', quantity: 65, category: 'entree', status: 'prepped', scheduledTime: 'Post-Game' },
          ],
          hierarchy: {
            director: { name: 'Derrick Vance', title: 'Director of Field & Gameday Operations', radioChannel: 'Ch 2 - Field Command' },
            manager: { name: 'Franklin Pierce', title: 'Locker & Athlete Facilities Manager', status: 'on_duty', radioChannel: 'Ch 2 - Field Command' },
            assignedStaff: [
              { name: 'Sarah Collins', role: 'Visiting Locker Attendant', status: 'on_duty', shift: '08:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-aux-headliner',
        code: 'AUX-HEADLINER',
        name: 'Halftime Headliner Green Room & Dressing Suite A',
        department: 'entertainment_hospitality',
        type: 'aux_performer_room',
        capacity: 25,
        stadiumZone: 'South Tunnel Level 0 Backstage',
        level: '0',
        status: 'restricted',
        suiteDetails: {
          suiteNumber: 'GREEN-ROOM-A',
          suiteholder: 'Live Nation / Halftime Show Talent Artist',
          tier: 'VIP Performer Suite',
          hostName: 'Artist Tour Manager (Rider Verified)',
          guestCount: 18,
          beoNumber: 'BEO-SHOW-2026-001',
          beoPackageName: 'A-List Tour Hospitality Rider & Organic Green Room',
          menuPackage: 'Organic cold-pressed ginger turmeric shots, vegan sushi platter, Manuka honey, sparkling artisan water, Dom Pérignon',
          attendantName: 'Elena Rostova (VIP Artist Host)',
          beoPreOrders: [
            { id: 'hr-1', name: 'Organic Cold-Pressed Juice & Wellness Bar', quantity: 18, category: 'beverage', status: 'delivered', scheduledTime: '11:00 AM' },
            { id: 'hr-2', name: 'Artisan Vegan & Raw Sushi Tasting Platter', quantity: 4, category: 'appetizer', status: 'delivered', scheduledTime: '12:30 PM' },
            { id: 'hr-3', name: 'Dom Pérignon & Vintage Champagne (4 btls)', quantity: 4, category: 'bar', status: 'delivered', scheduledTime: 'Pre-Show' },
          ],
          hierarchy: {
            director: { name: 'Eleanor Vance', title: 'VP of Premium Hospitality', radioChannel: 'Ch 1 - Executive' },
            manager: { name: 'Natasha Romanova', title: 'Entertainment & Performer Host Lead', status: 'on_duty', radioChannel: 'Ch 6 - Backstage VIP' },
            assignedStaff: [
              { name: 'Elena Rostova', role: 'Dedicated Artist Host', status: 'on_duty', shift: '10:00 - Show End', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-aux-band',
        code: 'AUX-BAND',
        name: 'Performer Auxiliary Dressing Room B (Band & Production)',
        department: 'entertainment_hospitality',
        type: 'aux_performer_room',
        capacity: 40,
        stadiumZone: 'South Tunnel Level 0 Backstage',
        level: '0',
        status: 'restricted',
        suiteDetails: {
          suiteNumber: 'GREEN-ROOM-B',
          suiteholder: 'Halftime Show Musicians & Stage Production Crew',
          tier: 'Production Compound',
          guestCount: 35,
          beoNumber: 'BEO-SHOW-2026-002',
          beoPackageName: 'Band & Crew High-Energy Catering',
          menuPackage: 'Gourmet slider bar, energy drink tubs, artisan flatbreads, coffee & espresso bar',
          hierarchy: {
            director: { name: 'Eleanor Vance', title: 'VP of Premium Hospitality', radioChannel: 'Ch 1 - Executive' },
            manager: { name: 'Natasha Romanova', title: 'Entertainment & Performer Host Lead', status: 'on_duty', radioChannel: 'Ch 6 - Backstage VIP' },
            assignedStaff: [
              { name: 'Corey Taylor', role: 'Band Hospitality Runner', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-aux-referee',
        code: 'AUX-REFS',
        name: 'Referees & League Officials Operations Locker Room',
        department: 'facilities_operations',
        type: 'aux_performer_room',
        capacity: 15,
        stadiumZone: 'North Tunnel Level 0',
        level: '0',
        status: 'restricted',
        suiteDetails: {
          suiteNumber: 'OFFICIALS-01',
          suiteholder: 'League Officiating Crew & Replay Command',
          tier: 'Official Operations',
          guestCount: 12,
          beoNumber: 'BEO-LEAGUE-2026-001',
          beoPackageName: 'Officials Pre-Game & Halftime Refreshment',
          menuPackage: 'Fresh fruit platters, energy protein bars, gourmet coffee, sports drinks',
          hierarchy: {
            director: { name: 'Derrick Vance', title: 'Director of Field & Gameday Operations', radioChannel: 'Ch 2 - Field Command' },
            manager: { name: 'Franklin Pierce', title: 'Locker & Athlete Facilities Manager', status: 'on_duty', radioChannel: 'Ch 2 - Field Command' },
            assignedStaff: [
              { name: 'Tyler Brooks', role: 'Officials Hospitality Attendant', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-aux-cheer',
        code: 'AUX-CHEER',
        name: 'Cheer & Mascot Aux Staging Locker Room',
        department: 'facilities_operations',
        type: 'aux_performer_room',
        capacity: 35,
        stadiumZone: 'East Tunnel Level 0',
        level: '0',
        status: 'open',
        suiteDetails: {
          suiteNumber: 'SPIRIT-01',
          suiteholder: 'Stadium Entertainment & Mascot Team',
          tier: 'Performer Dressing',
          guestCount: 30,
          menuPackage: 'Hydration tubs, fresh wraps, energy snacks',
          hierarchy: {
            director: { name: 'Derrick Vance', title: 'Director of Field & Gameday Operations', radioChannel: 'Ch 2 - Field Command' },
            manager: { name: 'Franklin Pierce', title: 'Locker & Athlete Facilities Manager', status: 'on_duty', radioChannel: 'Ch 2 - Field Command' },
            assignedStaff: [
              { name: 'Paige Morgan', role: 'Cheer Compound Attendant', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
    ],
  },

  // ── 5. LUXURY SUITES (LEVEL 300 & 400 · 80 SUITES) ─────────────────────
  {
    id: 'zone-300-suites',
    name: 'Luxury Suites & Loge Boxes (Level 300 & 400 · 80 Suites)',
    code: 'SUITES-300-400',
    level: '3',
    department: 'premium_hospitality',
    category: 'luxury_suites',
    unitsCount: 80,
    openCount: 80,
    alertCount: 0,
    units: [
      // ── Level 300 West Sideline Founders Suites (301–320) ──
      {
        id: 'u-301',
        code: 'SUITE-301',
        name: 'Suite 301 · Founders Skybox (Apex Global)',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 28,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '301',
          suiteholder: 'Apex Global Technologies',
          tier: 'Founders Suite',
          hostName: 'Marcus Sterling (VP VIP Hospitality)',
          guestCount: 26,
          beoNumber: 'BEO-NFL-2026-901',
          beoPackageName: 'Touchdown Luxury Banquet & Raw Bar',
          menuPackage: 'Prime Rib carving board, artisanal sliders, chilled Gulf shrimp, premium open bar',
          attendantName: 'Sarah Jenkins (Lead Attendant)',
          beoPreOrders: [
            { id: 'po-301-1', name: 'Prime Rib Carving Station w/ Au Jus & Horseradish', quantity: 26, category: 'entree', status: 'delivered', scheduledTime: 'Kickoff - 30m' },
            { id: 'po-301-2', name: 'Jumbo Poached Gulf Shrimp Cocktail Platter', quantity: 2, category: 'appetizer', status: 'delivered', scheduledTime: 'Pre-Game', dietaryNotes: 'Contains Shellfish' },
            { id: 'po-301-3', name: 'Dom Pérignon Vintage Champagne (3 btls)', quantity: 3, category: 'bar', status: 'delivered', scheduledTime: 'Pre-Game' },
            { id: 'po-301-4', name: 'Artisanal Truffle Mac & Vermont White Cheddar', quantity: 2, category: 'entree', status: 'active', scheduledTime: 'Kickoff' },
            { id: 'po-301-5', name: 'Executive Pastry Chef Grand Dessert Cart', quantity: 26, category: 'dessert', status: 'prepped', scheduledTime: 'Halftime' },
          ],
          inSuiteOrders: [
            { id: 'iso-301-1', orderedAt: '1:15 PM (Q1 08:42)', orderedBy: 'Suite Host Tablet', items: '2x Casamigos Reposado Carafe, 1x Extra Ice Bucket', totalCents: 24000, status: 'fulfilled' },
            { id: 'iso-301-2', orderedAt: '1:50 PM (Q2 02:15)', orderedBy: 'Attendant Alice T.', items: '1x Crispy Hot Wings Platter (30ct), 4x Diet Coke', totalCents: 9500, status: 'delivering' },
          ],
          hierarchy: {
            director: { name: 'Eleanor Vance', title: 'VP of Premium Hospitality', radioChannel: 'Ch 1 - Executive' },
            manager: { name: 'Sarah Jenkins', title: 'Suite Level 300 Floor Manager', status: 'on_duty', radioChannel: 'Ch 4 - Suites North' },
            assignedStaff: [
              { name: 'Alice Taylor', role: 'Lead Suite Attendant', status: 'on_duty', shift: '10:00 - Close', geofenceVerified: true },
              { name: 'Marcus Chen', role: 'Hospitality Runner', status: 'on_duty', shift: '11:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-302',
        code: 'SUITE-302',
        name: 'Suite 302 · Redline Private Capital Skybox',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 24,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '302',
          suiteholder: 'Redline Private Capital',
          tier: 'Executive Luxury Suite',
          hostName: 'Victoria Hastings',
          guestCount: 22,
          beoNumber: 'BEO-NFL-2026-902',
          beoPackageName: 'Gridiron Gourmet Feast & Craft Spirits',
          menuPackage: 'Smoked tenderloin, hot honey chicken sliders, charcuterie tower, specialty cocktails',
          attendantName: 'David Miller (Lead)',
        },
      },
      {
        id: 'u-303',
        code: 'SUITE-303',
        name: 'Suite 303 · Summit Wealth Partners',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 20,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '303',
          suiteholder: 'Summit Wealth Partners',
          tier: 'Executive Luxury Suite',
          guestCount: 18,
          beoNumber: 'BEO-NFL-2026-903',
          beoPackageName: 'Artisan BBQ & Tap Platter',
          menuPackage: 'Smoked brisket, jalapeño sausage, mac & cheese, craft beer',
        },
      },
      {
        id: 'u-304',
        code: 'SUITE-304',
        name: 'Suite 304 · Chevron Energy Skybox',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 26,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '304',
          suiteholder: 'Chevron Global Energy',
          tier: 'Founders Suite',
          guestCount: 24,
          beoNumber: 'BEO-NFL-2026-904',
          beoPackageName: 'Prime Steaks & Vintage Cellar',
        },
      },
      {
        id: 'u-305',
        code: 'SUITE-305',
        name: 'Suite 305 · Valero Refining Suite',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 22,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '305',
          suiteholder: 'Valero Energy Corporation',
          tier: 'Executive Luxury Suite',
          guestCount: 20,
          beoNumber: 'BEO-NFL-2026-905',
          beoPackageName: 'Texas Smokehouse & Craft Ale Bar',
        },
      },
      {
        id: 'u-306',
        code: 'SUITE-306',
        name: 'Suite 306 · H-E-B Culinary Skybox',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 30,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '306',
          suiteholder: 'H-E-B Food & Grocery',
          tier: 'Founders Suite',
          guestCount: 28,
          beoNumber: 'BEO-NFL-2026-906',
          beoPackageName: 'Texas Prime Brisket & Farm Fresh Tapas',
        },
      },
      {
        id: 'u-307',
        code: 'SUITE-307',
        name: 'Suite 307 · ConocoPhillips Energy Skybox',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 24,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '307',
          suiteholder: 'ConocoPhillips Corporation',
          tier: 'Executive Luxury Suite',
          guestCount: 22,
          beoNumber: 'BEO-NFL-2026-907',
          beoPackageName: 'Prime Tenderloin & Cabernet Reserve',
        },
      },
      {
        id: 'u-308',
        code: 'SUITE-308',
        name: 'Suite 308 · Sysco Corporate Dining Suite',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 26,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '308',
          suiteholder: 'Sysco Corporation',
          tier: 'Founders Suite',
          guestCount: 25,
          beoNumber: 'BEO-NFL-2026-908',
          beoPackageName: 'Artisan Chef Signature Tasting Menu',
        },
      },
      {
        id: 'u-309',
        code: 'SUITE-309',
        name: 'Suite 309 · Baker Hughes Technology Skybox',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 22,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '309',
          suiteholder: 'Baker Hughes',
          tier: 'Executive Luxury Suite',
          guestCount: 20,
          beoNumber: 'BEO-NFL-2026-909',
          beoPackageName: 'Gourmet Sliders & Craft Spirits',
        },
      },
      {
        id: 'u-310',
        code: 'SUITE-310',
        name: 'Suite 310 · Halliburton 50-Yardline Box',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 32,
        stadiumZone: 'West Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '310',
          suiteholder: 'Halliburton Energy Services',
          tier: 'Founders Midfield Box',
          guestCount: 30,
          beoNumber: 'BEO-NFL-2026-910',
          beoPackageName: 'Presidential Gold Hospitality Package',
        },
      },
      ...Array.from({ length: 10 }, (_, i) => {
        const num = 311 + i;
        const sponsors = ['Crown Castle', 'CenterPoint Energy', 'Phillips 66', 'Occidental Petroleum', 'NRG Energy', 'Woodside Energy', 'LyondellBasell', 'Houston Methodist', 'Memorial Hermann', 'MD Anderson Cancer Center'];
        const sponsor = sponsors[i] ?? `Corporate Partner ${num}`;
        return {
          id: `u-${num}`,
          code: `SUITE-${num}`,
          name: `Suite ${num} · ${sponsor}`,
          department: 'premium_hospitality',
          type: 'premium_suite' as const,
          capacity: 22,
          stadiumZone: 'West Suite Tower Level 3',
          level: '3',
          status: 'open' as const,
          suiteDetails: {
            suiteNumber: String(num),
            suiteholder: sponsor,
            tier: 'Executive Luxury Suite',
            guestCount: 20,
            beoNumber: `BEO-NFL-2026-${num}`,
            beoPackageName: 'Gourmet Gameday Suite Buffet',
            menuPackage: 'Prime carving meats, artisan flatbreads, craft beverages',
          },
        };
      }),

      // ── Level 300 East Sideline Corporate Suites (321–340) ──
      {
        id: 'u-321',
        code: 'SUITE-321',
        name: 'Suite 321 · Vanguard Tech Skybox',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 24,
        stadiumZone: 'East Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '321',
          suiteholder: 'Vanguard Tech Corporation',
          tier: 'Executive Luxury Suite',
          guestCount: 22,
          beoNumber: 'BEO-NFL-2026-921',
          beoPackageName: 'Coastal Seafood & Champagne',
        },
      },
      {
        id: 'u-322',
        code: 'SUITE-322',
        name: 'Suite 322 · Meridian Health Skybox',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 26,
        stadiumZone: 'East Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '322',
          suiteholder: 'Meridian Health Network',
          tier: 'Founders Suite',
          guestCount: 24,
          beoNumber: 'BEO-NFL-2026-922',
          beoPackageName: 'Grand Mediterranean Tapas & Prime Tenderloin',
        },
      },
      {
        id: 'u-323',
        code: 'SUITE-323',
        name: 'Suite 323 · NFL League Executive Box',
        department: 'premium_hospitality',
        type: 'premium_suite',
        capacity: 35,
        stadiumZone: 'East Suite Tower Level 3',
        level: '3',
        status: 'open',
        suiteDetails: {
          suiteNumber: '323',
          suiteholder: 'NFL League Executive Office',
          tier: 'Commissioner Skybox',
          guestCount: 32,
          beoNumber: 'BEO-NFL-2026-923',
          beoPackageName: 'Presidential Diamond Hospitality Banquet',
        },
      },
      ...Array.from({ length: 17 }, (_, i) => {
        const num = 324 + i;
        const sponsors = ['Waste Management', 'Kinder Morgan', 'Enterprise Products', 'KBR Inc', 'Cheniere Energy', 'Calpine', 'Insperity', 'Prosperity Bancshares', 'Group 1 Automotive', 'Quanta Services', 'Westlake Chemical', 'Service Corporation', 'Camden Property', 'Coterra Energy', 'APA Corporation', 'Southwestern Energy', 'EOG Resources'];
        const sponsor = sponsors[i] ?? `Corporate Partner ${num}`;
        return {
          id: `u-${num}`,
          code: `SUITE-${num}`,
          name: `Suite ${num} · ${sponsor}`,
          department: 'premium_hospitality',
          type: 'premium_suite' as const,
          capacity: 22,
          stadiumZone: 'East Suite Tower Level 3',
          level: '3',
          status: 'open' as const,
          suiteDetails: {
            suiteNumber: String(num),
            suiteholder: sponsor,
            tier: 'Executive Luxury Suite',
            guestCount: 20,
            beoNumber: `BEO-NFL-2026-${num}`,
            beoPackageName: 'Executive Gameday Spread & Bar',
            menuPackage: 'Gourmet slider bar, charcuterie towers, open premium bar',
          },
        };
      }),

      // ── Level 300 North & South Endzone Suites (341–360) ──
      ...Array.from({ length: 20 }, (_, i) => {
        const num = 341 + i;
        const isNorth = i < 10;
        const sponsors = ['Texas Medical Center', 'United Airlines', 'BMC Software', 'American Campus', 'Academy Sports', 'Kirby Corp', 'Powell Industries', 'Stewart Information', 'Comfort Systems', 'Main Street Capital', 'Stage Stores', 'Landmark Graphics', 'Weatherford', 'Nabors Industries', 'Oceaneering', 'McDermott International', 'Helix Energy', 'Noble Corp', 'Transocean', 'Diamond Offshore'];
        const sponsor = sponsors[i] ?? `Endzone Partner ${num}`;
        return {
          id: `u-${num}`,
          code: `SUITE-${num}`,
          name: `Suite ${num} · ${sponsor}`,
          department: 'premium_hospitality',
          type: 'premium_suite' as const,
          capacity: 24,
          stadiumZone: isNorth ? 'North Endzone Suite Ring' : 'South Endzone Suite Ring',
          level: '3',
          status: 'open' as const,
          suiteDetails: {
            suiteNumber: String(num),
            suiteholder: sponsor,
            tier: isNorth ? 'North Touchdown Suite' : 'South Touchdown Suite',
            guestCount: 22,
            beoNumber: `BEO-NFL-2026-${num}`,
            beoPackageName: 'Touchdown Terrace Buffet & Spirits',
            menuPackage: 'BBQ ribs, Texas sausages, mac & cheese, craft beer tubs',
          },
        };
      }),

      // ── Level 400 Loge & Chairman Suites (401–440) ──
      ...Array.from({ length: 40 }, (_, i) => {
        const num = 401 + i;
        const isWest = i < 20;
        return {
          id: `u-${num}`,
          code: `SUITE-${num}`,
          name: `Suite ${num} · ${isWest ? 'West' : 'East'} Loge Suite ${num}`,
          department: 'premium_hospitality',
          type: 'premium_suite' as const,
          capacity: 18,
          stadiumZone: isWest ? 'Level 400 West Loge' : 'Level 400 East Loge',
          level: '4',
          status: 'open' as const,
          suiteDetails: {
            suiteNumber: String(num),
            suiteholder: `Loge Member #${num}`,
            tier: 'Level 400 Loge Suite',
            guestCount: 16,
            beoNumber: `BEO-NFL-2026-${num}`,
            beoPackageName: 'Loge Box Gameday Hospitality',
            menuPackage: 'Artisan sandwiches, chips & dip, craft beers, wine',
          },
        };
      }),
    ],
  },

  // ── 6. CLUB LEVEL 200 ───────────────────────────────────────────────────
  {
    id: 'zone-200-club',
    name: '200 Club Level & Lounges',
    code: '200-CLUB',
    level: '2',
    department: 'premium_hospitality',
    category: 'club_level',
    unitsCount: 2,
    openCount: 2,
    alertCount: 0,
    units: [
      {
        id: 'u-club-east',
        code: 'CLUB-EAST',
        name: 'Champions Club East & Oyster Bar',
        department: 'premium_hospitality',
        type: 'club_lounge',
        capacity: 450,
        stadiumZone: 'East Club Tier Level 2',
        level: '2',
        status: 'open',
        standDetails: {
          standNumber: 'CL-201',
          concept: 'Chef Action Oyster Bar, Carving Station, Craft Mixology',
          terminalCount: 12,
          cashGrossCents: 4200000,
        },
      },
      {
        id: 'u-club-west',
        code: 'CLUB-WEST',
        name: 'Gridiron Club West & 50-Yardline Bar',
        department: 'premium_hospitality',
        type: 'club_lounge',
        capacity: 480,
        stadiumZone: 'West Club Tier Level 2',
        level: '2',
        status: 'open',
        standDetails: {
          standNumber: 'CL-202',
          concept: 'Panoramic 50-Yardline Premium Taproom & Grill',
          terminalCount: 14,
          cashGrossCents: 4850000,
        },
      },
    ],
  },

  // ── 7. UPPER DECK 400 ───────────────────────────────────────────────────
  {
    id: 'zone-400-upper',
    name: '400 Upper Deck Concourse & Skyline Bars',
    code: '400-UPPER',
    level: '4',
    department: 'concessions',
    category: 'upper_deck',
    unitsCount: 3,
    openCount: 3,
    alertCount: 0,
    units: [
      {
        id: 'u-upper-401',
        code: 'SKY-401',
        name: 'Skyline Terrace Bar & Craft Drafts',
        department: 'concessions',
        type: 'upper_concessions',
        capacity: null,
        stadiumZone: 'Upper Deck South Skyline',
        level: '4',
        status: 'open',
        standDetails: {
          standNumber: 'UD-401',
          concept: 'High-Volume Canned Spirits & Draft Express',
          terminalCount: 8,
          cashGrossCents: 1650000,
        },
      },
      {
        id: 'u-upper-408',
        code: 'UD-408',
        name: 'Upper North 408 · Redzone Tenders & Fries',
        department: 'concessions',
        type: 'upper_concessions',
        capacity: null,
        stadiumZone: 'Upper Deck North',
        level: '4',
        status: 'open',
        standDetails: {
          standNumber: 'UD-408',
          concept: 'Crispy Chicken Baskets, Jumbo Pretzels, Sodas',
          terminalCount: 6,
          cashGrossCents: 1100000,
        },
      },
    ],
  },
  // ── 8. MAIN BRANDED ENTRY GATES ─────────────────────────────────────────
  {
    id: 'zone-stadium-gates',
    name: 'Main Stadium Entry Gates & Welcome Plazas',
    code: 'STAD-GATES',
    level: '1',
    department: 'guest_services',
    category: 'stadium_gates',
    unitsCount: 4,
    openCount: 4,
    alertCount: 0,
    units: [
      {
        id: 'u-gate-ford',
        code: 'GATE-FORD',
        name: 'Ford Gate (North) · VIP Arrival & North Concourse Hub',
        department: 'guest_services',
        type: 'entry_gate',
        capacity: 12000,
        stadiumZone: 'North Entrance Plaza',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'GATE-FORD-01',
          concept: 'Ford Signature Blue Plaza · VIP Guest Welcome, Ticket Scanning & Event Concierge',
          terminalCount: 16,
          cashGrossCents: 420000,
          inSeatOrders: [],
          hierarchy: {
            director: { name: 'Elena Rostova', title: 'Director of Guest Services & Fan Experience', radioChannel: 'Ch 1 - Command' },
            manager: { name: 'Marcus Sterling', title: 'North Gate Operations Manager', status: 'on_duty', radioChannel: 'Ch 4 - Gates & Security' },
            assignedStaff: [
              { name: 'Chloe Vance', role: 'VIP Arrival Lead', status: 'on_duty', shift: '09:00 - Close', geofenceVerified: true },
              { name: 'Julian Ortiz', role: 'Turnstile & Scanner Tech', status: 'on_duty', shift: '09:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-gate-kroger',
        code: 'GATE-KROGER',
        name: 'Kroger Gate (South) · South Plaza & Fan Express Entry',
        department: 'guest_services',
        type: 'entry_gate',
        capacity: 15000,
        stadiumZone: 'South Entrance Plaza',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'GATE-KROGER-01',
          concept: 'Kroger Fresh Gate · Express Turnstiles, Gameday Merch & Quick Refreshment Depot',
          terminalCount: 20,
          cashGrossCents: 680000,
          inSeatOrders: [],
          hierarchy: {
            director: { name: 'Elena Rostova', title: 'Director of Guest Services & Fan Experience', radioChannel: 'Ch 1 - Command' },
            manager: { name: 'Brenda Washington', title: 'South Gate Operations Manager', status: 'on_duty', radioChannel: 'Ch 4 - Gates & Security' },
            assignedStaff: [
              { name: 'Devon Miles', role: 'South Turnstile Supervisor', status: 'on_duty', shift: '09:00 - Close', geofenceVerified: true },
              { name: 'Kendra Harris', role: 'Guest Hospitality Greeter', status: 'on_duty', shift: '09:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-gate-p66',
        code: 'GATE-P66',
        name: 'Phillips 66 Gate (West) · Luxury Suite & Media Credential Entry',
        department: 'guest_services',
        type: 'entry_gate',
        capacity: 8000,
        stadiumZone: 'West Entrance Plaza',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'GATE-P66-01',
          concept: 'Phillips 66 Premium Gate · Dedicated Suiteholder Fast-Track, VIP Elevators & Media Check-In',
          terminalCount: 12,
          cashGrossCents: 310000,
          inSeatOrders: [],
          hierarchy: {
            director: { name: 'Elena Rostova', title: 'Director of Guest Services & Fan Experience', radioChannel: 'Ch 1 - Command' },
            manager: { name: 'Arthur Pendelton', title: 'West Premium Entry Manager', status: 'on_duty', radioChannel: 'Ch 4 - Gates & Security' },
            assignedStaff: [
              { name: 'Sofia Rodriguez', role: 'Suiteholder VIP Concierge', status: 'on_duty', shift: '09:30 - Close', geofenceVerified: true },
              { name: 'Tyler Reed', role: 'Credential Verification Lead', status: 'on_duty', shift: '09:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
      {
        id: 'u-gate-xfinity',
        code: 'GATE-XFINITY',
        name: 'xfinity Gate (East) · East Concourse & Club Escalators',
        department: 'guest_services',
        type: 'entry_gate',
        capacity: 14000,
        stadiumZone: 'East Entrance Plaza',
        level: '1',
        status: 'open',
        standDetails: {
          standNumber: 'GATE-XFINITY-01',
          concept: 'xfinity Gigabit Gate · Club Level Direct Escalators & High-Speed Fan Check-in',
          terminalCount: 18,
          cashGrossCents: 540000,
          inSeatOrders: [],
          hierarchy: {
            director: { name: 'Elena Rostova', title: 'Director of Guest Services & Fan Experience', radioChannel: 'Ch 1 - Command' },
            manager: { name: 'Darnell Jackson', title: 'East Gate Operations Manager', status: 'on_duty', radioChannel: 'Ch 4 - Gates & Security' },
            assignedStaff: [
              { name: 'Aaliyah Brown', role: 'Club Level Access Host', status: 'on_duty', shift: '09:30 - Close', geofenceVerified: true },
              { name: 'Lucas Chang', role: 'Turnstile Tech Specialist', status: 'on_duty', shift: '09:00 - Close', geofenceVerified: true },
            ],
          },
        },
      },
    ],
  },
];

