import { router } from 'expo-router';
import { ScrollView, View } from 'react-native';
import { Button } from 'react-native-paper';
import { CommandSurface, CommandText, StatusPill } from '../components/FutureUI';
import { api } from '../lib/railway-api';
import { useQueryState } from '../lib/railway-hooks';
import { spacing, useDesignTheme } from '../lib/theme';
import { asArray } from '../lib/format';
type Integration = { pos: Array<{ provider: string; status: string; lastSyncAt?: string | null }>; reservations: Array<{ provider: string; status: string; lastSyncAt?: string | null }>; last30Days: { posChecks: number }; canonicalInventoryItems: number; manualCsvImportAvailable: boolean; providerIntegrations: string };
export default function IntegrationReadinessScreen() { const palette = useDesignTheme(); const query = useQueryState<Integration>(api.stadium.getIntegrationReadiness, {}); const data = query.data; const rows = [...asArray(data?.pos).map((row) => ({ ...row, kind: 'POS' })), ...asArray(data?.reservations).map((row) => ({ ...row, kind: 'Reservations' }))]; return <ScrollView style={{ flex: 1, backgroundColor: 'transparent' }} contentContainerStyle={{ padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xxl }}><Button mode="text" textColor={palette.primary} onPress={() => router.back()}>Back</Button><CommandSurface palette={palette} strong style={{ gap: spacing.xs }}><CommandText palette={palette} variant="label">Data connections</CommandText><CommandText palette={palette} variant="hero">Integration readiness</CommandText><CommandText palette={palette} variant="caption">Provider health plus approved CSV/manual fallback paths for the pilot.</CommandText></CommandSurface><CommandSurface palette={palette} style={{ gap: spacing.sm }}><CommandText palette={palette} variant="title">Connected providers</CommandText>{rows.length ? rows.map((row) => <View key={`${row.kind}-${row.provider}`} style={{ flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: palette.border, paddingVertical: spacing.xs }}><CommandText palette={palette} variant="body">{row.kind} · {row.provider}</CommandText><StatusPill palette={palette} tone={row.status === 'connected' ? 'good' : 'warn'}>{row.status}</StatusPill></View>) : <CommandText palette={palette} variant="caption">No authenticated provider connection is configured.</CommandText>}</CommandSurface><CommandSurface palette={palette} style={{ gap: spacing.xs }}><CommandText palette={palette} variant="title">Pilot data coverage</CommandText><CommandText palette={palette} variant="body">POS checks, last 30 days: {data?.last30Days?.posChecks ?? 0}</CommandText><CommandText palette={palette} variant="body">Canonical inventory items: {data?.canonicalInventoryItems ?? 0}</CommandText><CommandText palette={palette} variant="body">CSV/manual import: {data?.manualCsvImportAvailable ? 'Available' : 'Unavailable'}</CommandText></CommandSurface></ScrollView>; }

// Expo Router renders this boundary around this route only, so a render
// error here shows a recovery card in place instead of unmounting the
// whole app through the root boundary.
export { RouteErrorBoundary as ErrorBoundary } from '../components/ErrorBoundary';
